# Generated by Django 3.2.6 on 2021-08-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='cart',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='design',
            name='cart_pk',
        ),
        migrations.AddField(
            model_name='design',
            name='cart_id',
            field=models.CharField(default=1, max_length=100, verbose_name='cart id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderline'),
        ),
        migrations.AlterField(
            model_name='design',
            name='cart_line',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
