# Generated by Django 3.2.6 on 2021-08-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20210810_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='order',
        ),
    ]
