# Generated by Django 3.2.6 on 2021-08-11 06:12

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvideo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
    ]
