# Generated by Django 3.2.6 on 2021-08-10 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rzp_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='razorpay_order_id')),
                ('signature', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Created', 'CREATED'), ('Authorized', 'AUTHORIZED'), ('Captured', 'CAPTURED'), ('Refunded', 'REFUNDED'), ('Failed', 'FAILED')], default='Created', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charged_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gateway_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rzp_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='razorpay_order_id')),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Holder Name')),
                ('card_holder_network', models.CharField(blank=True, max_length=100, null=True, verbose_name='card Holder Network')),
                ('card_issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='card issuer')),
                ('card_last_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='card last 4 digit numebers')),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_token', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
