# Generated by Django 3.2.6 on 2021-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210811_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Created', 'CREATED'), ('Authorized', 'AUTHORIZED'), ('Captured', 'CAPTURED'), ('Refunded', 'REFUNDED'), ('PartiallyRefunded', 'PARTIALLY REFUNDED'), ('Failed', 'FAILED')], default='Created', max_length=50),
        ),
    ]
