# Generated by Django 3.2.6 on 2021-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210811_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
