# Generated by Django 3.2.6 on 2021-08-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210810_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='created_by',
            new_name='user',
        ),
    ]
