# Generated by Django 3.2.6 on 2021-08-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_created_by_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='created_by',
        ),
    ]
