# Generated by Django 3.2.6 on 2021-08-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_user_address_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='basic_amount',
            new_name='shipping_charges',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_chrages',
        ),
    ]
