# Generated by Django 3.2.6 on 2021-08-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('partiallyRefunded', 'PartiallyRefunded')], default='Pending', max_length=50),
        ),
    ]
