# Generated by Django 3.2.6 on 2021-08-11 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=100, verbose_name='cart id')),
                ('cart_line', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='order_image/')),
                ('video', models.FileField(upload_to='order_video/')),
                ('order_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='design', to='order.orderline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
