# Generated by Django 3.2.6 on 2021-08-12 06:25

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210812_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='order_image'),
        ),
    ]
